# Generated by Django 2.2.1 on 2019-05-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanmark',
            name='num',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
