# Generated by Django 2.2.1 on 2019-05-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
